export const ERROR_CODES = {
  EMAIL_ALREADY_IN_WAITLIST: "email_already_in_waitlist",
  DOMAIN_NOT_ALLOWED: "domain_not_allowed",
  WAITLIST_FULL: "waitlist_full",
  RATE_LIMIT_EXCEEDED: "rate_limit_exceeded",
  WAITLIST_NOT_ENABLED: "waitlist_not_enabled",
  INVALID_ENTRY: "validation_error",
  UNAUTHORIZED: "unauthorized",
  WAITLIST_ENTRY_NOT_FOUND: "waitlist_entry_not_found",
} as const;

export const ERROR_MESSAGES = {
  EMAIL_ALREADY_IN_WAITLIST: "Email already in waitlist",
  EMAIL_ALREADY_REQUESTED: "Email already requested",
  DOMAIN_NOT_ALLOWED: "Email domain not allowed",
  WAITLIST_FULL: "Waitlist is full",
  RATE_LIMIT_EXCEEDED: "Too many requests, please try again later",
  WAITLIST_NOT_ENABLED: "Waitlist is not enabled",
  INVALID_ENTRY: "Invalid entry.",
  UNAUTHORIZED: "Only admin can perform this action",
  WAITLIST_ENTRY_NOT_FOUND: "Waitlist entry not found",
} as const;

export const ERROR_MESSAGES_MAP = {
  [ERROR_CODES.EMAIL_ALREADY_IN_WAITLIST]: ERROR_MESSAGES.EMAIL_ALREADY_IN_WAITLIST,
  [ERROR_CODES.DOMAIN_NOT_ALLOWED]: ERROR_MESSAGES.DOMAIN_NOT_ALLOWED,
  [ERROR_CODES.WAITLIST_FULL]: ERROR_MESSAGES.WAITLIST_FULL,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: ERROR_MESSAGES.RATE_LIMIT_EXCEEDED,
  [ERROR_CODES.WAITLIST_NOT_ENABLED]: ERROR_MESSAGES.WAITLIST_NOT_ENABLED,
  [ERROR_CODES.INVALID_ENTRY]: ERROR_MESSAGES.INVALID_ENTRY,
  [ERROR_CODES.UNAUTHORIZED]: ERROR_MESSAGES.UNAUTHORIZED,
  [ERROR_CODES.WAITLIST_ENTRY_NOT_FOUND]: ERROR_MESSAGES.WAITLIST_ENTRY_NOT_FOUND,
} as const;
